export default {
    FETCH_LANCAMENTOS: 'FETCH_LANCAMENTOS',
    FETCH_PLANEJAMENTO: 'FETCH_PLANEJAMENTO',
    SAVE_PLANEJAMENTO: 'SAVE_PLANEJAMENTO',
    FETCHED: 'FETCHED',
    SET_MES_CORRENTE: 'SET_MES_CORRENTE',
    SET_CATEGORIA_CORRENTE: 'SET_CATEGORIA_CORRENTE',
    LOGIN: 'LOGIN',
    LOGOUT: 'LOGOUT',
    ADD_LANCAMENTOS: 'ADD_LANCAMENTOS',
    ADD_CATEGORIA: 'ADD_CATEGORIA',
    SET_CATEGORIA: 'SET_CATEGORIA',
    FETCH_CONFIG: 'FETCH_CONFIG',
    SET_MEIO_PAGAMENTO: 'SET_MEIO_PAGAMENTO',
    FETCH_ACOMPANHAMENTO: 'FETCH_ACOMPANHAMENTO'
};
